export const validEmployeeNumber = /^\d{4}$/;
export const validName = /^[A-Z][a-z]{1,}(?:(?:[- ][A-Z][a-z]{1,})?)*$/;
export const validPhoneNumber = /^\d{3}-\d{3}-\d{4}$/;
export const validEmail = /^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z-.]+$/;
export const validRole = /^[A-Z][a-zA-Z]*$/;
export const validColorHexCode = /^#([A-F0-9]{6}|[A-F0-9]{3})$/;
export const validHourlyRate = /^[1-9]\d{1,2}(\.\d{1,2})?$/;
export const validBarcodeNumber = /^\d{16}$/;
export const validSkillPoints = /^(?:[1-9]|10)$/;
export const validPassword = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
